name: Release

on:
  push:
    branches: ["main"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up nodejs
        uses: actions/setup-node@v3
      - name: Set up Hexo
        run: |
          npm install hexo
      - name: Build
        run: |
          hexo g
      - name: Deploy
        uses: y4code/hexo-deploy-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_REPOSITORY: it-briefcode/it-briefcode.github.io # The repository the action should deploy to.
        BRANCH: master  # The branch the action should deploy to.
        PUBLISH_DIR: ./public # The folder the action should deploy.
          hexo
